services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=billetter-db
      - POSTGRES_PASSWORD=billetter
      - POSTGRES_USER=billetter
    ports:
      - 15433:5432
    volumes:
      - biletter-db:/var/lib/postgresql/data  # этот volume нужно определить

volumes:
  medtech_service_db:
