server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15433/billetter-db}
    username: ${DB_USERNAME:billetter}
    password: ${DB_PASSWORD:billetter}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none